# Generated by Django 4.2 on 2024-05-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_api_user',
            field=models.BooleanField(default=False),
        ),
    ]
