# Generated by Django 4.2 on 2024-05-26 14:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_api_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='known_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('judaism', 'Judaism'), ('sikhism', 'Sikhism'), ('confucianism', 'Confucianism'), ('taoism', 'Taoism'), ('shinto', 'Shinto')], default='islam', max_length=60),
        ),
    ]
