# Generated by Django 5.0.3 on 2024-03-27 15:14

import django.contrib.sites.managers
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site', verbose_name='site')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True)),
                ('visitor_addressing', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_title', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('location_geo_code', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('name_logo', models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('home_page_picture', models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('about_picture', models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('mask_icon', models.FileField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('career_summary', models.TextField(blank=True, null=True)),
                ('education_header', models.TextField(blank=True, null=True)),
                ('education_footer', models.TextField(blank=True, null=True)),
                ('blog_page_title', models.TextField(blank=True, null=True)),
                ('blog_page_description', models.TextField(blank=True, null=True)),
                ('blog_page_picture', models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('project_page_title', models.TextField(blank=True, null=True)),
                ('project_page_description', models.TextField(blank=True, null=True)),
                ('project_page_picture', models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('service_page_title', models.TextField(blank=True, null=True)),
                ('service_page_description', models.TextField(blank=True, null=True)),
                ('service_page_picture', models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('contact_page_title', models.TextField(blank=True, null=True)),
                ('contact_page_description', models.TextField(blank=True, null=True)),
                ('contact_page_picture', models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('upwork_link', models.URLField(blank=True, null=True)),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
