# Generated by Django 5.0.3 on 2024-03-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='name_logo',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='name_logo_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='name_logo_svg_animate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
