# Generated by Django 5.0.3 on 2024-03-28 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_siteprofile_name_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='about_picture',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='blog_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['svg', 'json'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='contact_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['svg', 'json'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='home_page_picture',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='project_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['svg', 'json'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='service_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['svg', 'json'])]),
        ),
    ]
