# Generated by Django 5.0.3 on 2024-03-28 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_siteprofile_site'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_or_designation', models.CharField(max_length=100)),
                ('company_or_workplace', models.CharField(max_length=200)),
                ('worked_from', models.DateField()),
                ('worked_to', models.DateField()),
                ('currently_working_or_not', models.BooleanField(default=False)),
                ('background_color_class', models.CharField(max_length=20)),
                ('border_color_class', models.CharField(max_length=20)),
                ('col_width_class', models.CharField(max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='WhatDidThere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.experience')),
            ],
        ),
    ]
