# Generated by Django 5.0.3 on 2024-03-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_experience_whatdidthere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='background_color_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='border_color_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='col_width_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
