# Generated by Django 5.0.3 on 2024-03-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_experience_experience_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('freelance', 'Freelance'), ('full_time', 'Full time'), ('part_time', 'Part time'), ('contractual', 'Contractual'), ('remote', 'Remote')], default='full_time', max_length=20),
        ),
    ]
