# Generated by Django 5.0.3 on 2024-03-28 21:51

import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_experience_experience_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='experience',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
