# Generated by Django 5.0.3 on 2024-03-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_experience_managers'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsite', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='whatdidthere',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_experience', to='common.experience'),
        ),
    ]
