# Generated by Django 5.0.3 on 2024-03-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_experience_site_alter_whatdidthere_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatdidthere',
            name='item',
            field=models.TextField(),
        ),
    ]
