# Generated by Django 5.0.3 on 2024-03-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_experience_site_skillsandtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatdidthere',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_did', to='common.experience'),
        ),
        migrations.DeleteModel(
            name='SkillsAndTools',
        ),
    ]
