# Generated by Django 5.0.3 on 2024-03-28 22:20

import django.contrib.sites.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_whatdidthere_experience_delete_skillsandtools'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsAndTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(upload_to='skills_icons/')),
                ('name', models.CharField(max_length=100)),
                ('skill_percent', models.PositiveIntegerField()),
                ('working_for_years', models.PositiveIntegerField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_to_experience', to='common.experience')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_to_site', to='sites.site')),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
