# Generated by Django 5.0.3 on 2024-03-28 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_skillsandtools_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsandtools',
            name='icon_image',
            field=models.FileField(blank=True, null=True, upload_to='skills_icons/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
