# Generated by Django 5.0.3 on 2024-03-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_skillsandtools_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skills_marquee_direction',
            field=models.CharField(choices=[('freelance', 'Freelance'), ('full_time', 'Full time'), ('part_time', 'Part time'), ('contractual', 'Contractual'), ('remote', 'Remote')], default='left', max_length=20),
        ),
    ]
