# Generated by Django 5.0.3 on 2024-03-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_experience_skills_marquee_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='skills_marquee_direction',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right')], default='left', max_length=20),
        ),
    ]
