# Generated by Django 5.0.3 on 2024-03-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_alter_experience_skills_marquee_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='youtube_intro_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
