# Generated by Django 5.0.3 on 2024-03-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_siteprofile_youtube_intro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='text_color_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
