# Generated by Django 5.0.3 on 2024-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_experience_text_color_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
