# Generated by Django 5.0.3 on 2024-03-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_siteprofile_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='visitor_addressing',
        ),
    ]
