# Generated by Django 5.0.3 on 2024-03-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_remove_siteprofile_visitor_addressing'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='visitor_addressing_first',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='visitor_addressing_second',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
