# Generated by Django 5.0.3 on 2024-03-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_siteprofile_visitor_addressing_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='visitor_addressing_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='visitor_addressing_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
