# Generated by Django 5.0.3 on 2024-04-14 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_alter_siteprofile_visitor_addressing_first_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='siteprofile',
        #     name='name_logo_svg',
        #     field=models.ImageField(blank=True, null=True, upload_to='profile_logo/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        # ),
    ]
