# Generated by Django 5.0.3 on 2024-04-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_alter_siteprofile_name_logo_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='name_logo_svg',
        ),
    ]
