# Generated by Django 5.0.3 on 2024-04-17 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_siteprofile_name_logo_svg'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='siteprofile',
        #     name='name_logo_svg_animate',
        #     field=models.ImageField(blank=True, null=True, upload_to='profile_logo/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        # ),
    ]
