# Generated by Django 5.0.3 on 2024-04-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_alter_siteprofile_name_logo_svg_animate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='name_logo_svg_animate',
        ),
    ]
