# Generated by Django 5.0.3 on 2024-04-17 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_remove_siteprofile_name_logo_svg_animate'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='name_logo_svg_animate',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logo/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
