# Generated by Django 5.0.3 on 2024-04-20 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_siteprofile_name_logo_svg_animate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='name_logo_svg',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logo/', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='name_logo_svg_animate',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logo/', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
    ]
