# Generated by Django 5.0.3 on 2024-04-20 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_alter_siteprofile_name_logo_svg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='blog_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['svg', 'json', 'png'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='contact_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['svg', 'json', 'png'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='project_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['svg', 'json', 'png'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='service_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['svg', 'json', 'png'])]),
        ),
    ]
