# Generated by Django 5.0.3 on 2024-04-20 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_alter_siteprofile_blog_page_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='name_logo_svg',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='name_logo_svg_animate',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='name_logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='name_logo_big',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='blog_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='contact_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='project_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='service_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
