# Generated by Django 5.0.3 on 2024-04-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_alter_experience_managers_keyqualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='number_of_industries_works',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
