# Generated by Django 5.0.3 on 2024-04-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_siteprofile_number_of_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='interest',
            field=models.TextField(blank=True, help_text='Comma Separated', null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='languages',
            field=models.TextField(blank=True, help_text='Comma Separated', null=True),
        ),
    ]
