# Generated by Django 5.0.3 on 2024-04-30 19:16

import django.contrib.sites.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_siteprofile_interest_siteprofile_languages'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_zip', models.FileField(blank=True, upload_to='D:\\django_projects\\newhrdnsh\\temp_dir')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='sites.site')),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
