# Generated by Django 5.0.3 on 2024-04-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_sitetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetemplate',
            name='template_zip',
            field=models.FileField(blank=True, upload_to='temp_dir'),
        ),
    ]
