# Generated by Django 5.0.3 on 2024-04-30 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_alter_sitetemplate_template_zip'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetemplate',
            name='id',
        ),
        migrations.AlterField(
            model_name='sitetemplate',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='template', serialize=False, to='sites.site'),
        ),
    ]
