# Generated by Django 5.0.3 on 2024-04-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_remove_sitetemplate_id_alter_sitetemplate_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplate',
            name='template_dir',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
