# Generated by Django 5.0.3 on 2024-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_sitetemplate_template_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetemplate',
            name='template_dir',
            field=models.TextField(blank=True, null=True),
        ),
    ]
