# Generated by Django 4.2 on 2024-05-05 21:43

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('common', '0042_alter_sitetemplate_template_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_zip', models.FileField(blank=True, upload_to='temp_dir')),
                ('template_dir', models.TextField(blank=True, null=True)),
                ('sites', models.ManyToManyField(blank=True, related_name='templates', to='sites.site')),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('sites')),
            ],
        ),
        migrations.DeleteModel(
            name='SiteTemplate',
        ),
    ]
