# Generated by Django 4.2 on 2024-05-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_template_delete_sitetemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
