# Generated by Django 4.2 on 2024-05-06 05:58

import cms.mixins
from django.conf import settings
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0094_alter_blog_site'),
        ('sites', '0002_alter_domain_unique'),
        ('common', '0044_delete_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('public', 'Public'), ('unpublish', 'Unpublish'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('main_image', models.ImageField(upload_to=cms.mixins.get_upload_path)),
                ('thumbnail_image', models.ImageField(editable=False, upload_to=cms.mixins.get_upload_path)),
                ('template_zip', models.FileField(blank=True, upload_to='temp_dir')),
                ('template_dir', models.TextField(blank=True, null=True)),
                ('premium', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_category', to='cms.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_creators', to=settings.AUTH_USER_MODEL)),
                ('sites', models.ManyToManyField(blank=True, related_name='templates', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            bases=(cms.mixins.SaveAndImageOptimizationMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('sites')),
            ],
        ),
    ]
