# Generated by Django 4.2 on 2024-05-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_template'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='template',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='sites',
        ),
        migrations.AddField(
            model_name='template',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='templates', to='common.siteprofile'),
        ),
    ]
