# Generated by Django 4.2 on 2024-05-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_alter_template_managers_remove_template_sites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_template', to='common.template')),
            ],
        ),
    ]
