# Generated by Django 4.2 on 2024-05-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0047_selectedtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedTemplate',
        ),
    ]
