# Generated by Django 4.2 on 2024-05-06 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_delete_selectedtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_template', to='common.siteprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_template', to='common.template')),
            ],
        ),
    ]
