# Generated by Django 4.2 on 2024-05-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0049_selectedtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedtemplate',
            name='template',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'public'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_template', to='common.template'),
        ),
    ]
