# Generated by Django 4.2 on 2024-05-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0050_alter_selectedtemplate_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='profiles',
        ),
    ]
