# Generated by Django 4.2 on 2024-05-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_remove_template_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
    ]
