# Generated by Django 4.2 on 2024-05-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_remove_template_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='creator',
        ),
        migrations.DeleteModel(
            name='SelectedTemplate',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
