# Generated by Django 4.2 on 2024-05-06 10:56

import cms.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('common', '0053_remove_template_creator_delete_selectedtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('public', 'Public'), ('unpublish', 'Unpublish'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('main_image', models.ImageField(upload_to=cms.mixins.get_upload_path)),
                ('thumbnail_image', models.ImageField(editable=False, upload_to=cms.mixins.get_upload_path)),
                ('template_zip', models.FileField(blank=True, upload_to='temp_dir')),
                ('template_dir', models.TextField(blank=True, null=True)),
                ('premium', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_templates', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            bases=(cms.mixins.SaveAndImageOptimizationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SelectedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_template', to='common.siteprofile')),
                ('template', models.ForeignKey(blank=True, limit_choices_to={'status': 'public'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_template', to='common.template')),
            ],
        ),
    ]
