# Generated by Django 4.2 on 2024-05-07 16:28

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_template_selectedtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='profile_template_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg']), common.models.validate_file_size])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='common.siteprofile')),
            ],
        ),
    ]
