# Generated by Django 4.2 on 2024-05-07 16:49

import common.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_extraprofileimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraprofileimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_template_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg']), common.models.validate_file_size]),
        ),
    ]
