# Generated by Django 4.2 on 2024-05-07 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_alter_extraprofileimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['ico'])]),
        ),
    ]
