# Generated by Django 4.2 on 2024-05-07 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_alter_siteprofile_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='blog_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='contact_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='project_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='service_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg'])]),
        ),
    ]
