# Generated by Django 4.2 on 2024-05-07 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0058_alter_siteprofile_blog_page_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='blog_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='contact_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='project_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='service_page_picture',
            field=models.FileField(blank=True, null=True, upload_to='site_img_files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
