# Generated by Django 4.2 on 2024-05-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0060_personalizedemailsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalizedEmailSetting',
        ),
    ]
