# Generated by Django 4.2 on 2024-05-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('common', '0061_delete_personalizedemailsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedEmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='If provided Acknowledgement of contact form will be sent from this email and Contact Notification will receive here.', max_length=254, verbose_name='Sender Eamail')),
                ('host', models.CharField(help_text='Email will sent using this host', max_length=250)),
                ('port', models.IntegerField(help_text='SMTP port from your email configuration settings to sent email', verbose_name='SMTP port')),
                ('host_user', models.CharField(help_text='Email user', max_length=150)),
                ('host_password', models.CharField(help_text='Email Password', max_length=250)),
                ('acknowledge_message', models.TextField(help_text='Do not include Addrssing Or Email Signature. Just Write After Dear Client and before Best Regards', max_length=500)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_setting', to='sites.site')),
            ],
        ),
    ]
