# Generated by Django 4.2 on 2024-05-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0062_personalizedemailsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedemailsetting',
            name='email',
            field=models.EmailField(help_text='If provided Acknowledgement of contact form will be sent from this email and Contact Notification will receive here.', max_length=254, verbose_name='Sender Email'),
        ),
    ]
