# Generated by Django 4.2 on 2024-05-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0063_alter_personalizedemailsetting_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedtemplate',
            name='id',
        ),
        migrations.AlterField(
            model_name='selectedtemplate',
            name='profile',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='selected_template', serialize=False, to='common.siteprofile'),
        ),
    ]
