# Generated by Django 4.2 on 2024-05-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0064_remove_selectedtemplate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedtemplate',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='selected_template', serialize=False, to='common.siteprofile'),
        ),
    ]
