# Generated by Django 4.2 on 2024-05-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0065_alter_selectedtemplate_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
    ]
