# Generated by Django 4.2 on 2024-05-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_alter_experience_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraprofileimages',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='keyqualification',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='personalizedemailsetting',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='selectedtemplate',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='siteprofile',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='skillsandtools',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='whatdidthere',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
    ]
