# Generated by Django 4.2 on 2024-05-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0067_alter_extraprofileimages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['responsibility_or_designation', 'company_or_workplace'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='skillsandtools',
            options={'ordering': ['name', 'skill_percent'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='whatdidthere',
            options={'ordering': ['item'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
    ]
