# Generated by Django 4.2 on 2024-05-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('common', '0069_alter_template_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='sites.site', verbose_name='pk'),
        ),
    ]
