# Generated by Django 4.2 on 2024-05-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('common', '0070_alter_siteprofile_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedtemplate',
            name='profile',
            field=models.OneToOneField(help_text='Primary Key of the Selected Template', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='selected_template', serialize=False, to='common.siteprofile', verbose_name='PK'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='site',
            field=models.OneToOneField(help_text='Primary Key of the Profile', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='sites.site', verbose_name='PK'),
        ),
    ]
