# Generated by Django 4.2 on 2024-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0071_alter_selectedtemplate_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedemailsetting',
            name='acknowledge_message',
            field=models.TextField(blank=True, help_text='Do not include Addrssing Or Email Signature. Just Write After Dear Client and before Best Regards', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personalizedemailsetting',
            name='email',
            field=models.EmailField(blank=True, help_text='If provided Acknowledgement of contact form will be sent from this email and Contact Notification will receive here.', max_length=254, null=True, verbose_name='Sender Email'),
        ),
        migrations.AlterField(
            model_name='personalizedemailsetting',
            name='host',
            field=models.CharField(blank=True, help_text='Email will sent using this host', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personalizedemailsetting',
            name='host_password',
            field=models.CharField(blank=True, help_text='Email Password', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personalizedemailsetting',
            name='host_user',
            field=models.CharField(blank=True, help_text='Email user', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personalizedemailsetting',
            name='port',
            field=models.IntegerField(blank=True, help_text='SMTP port from your email configuration settings to sent email', null=True, verbose_name='SMTP port'),
        ),
    ]
