# Generated by Django 4.2 on 2024-05-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('common', '0072_alter_personalizedemailsetting_acknowledge_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizedemailsetting',
            name='id',
        ),
        migrations.AlterField(
            model_name='personalizedemailsetting',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personalized_setting', serialize=False, to='sites.site'),
        ),
    ]
