# Generated by Django 4.2 on 2024-05-13 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0073_remove_personalizedemailsetting_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyqualification',
            options={'ordering': ['-from_date', 'title'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='associate_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
