# Generated by Django 5.0.3 on 2024-04-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0084_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
