# Generated by Django 5.0.3 on 2024-04-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0086_alter_blog_created_at_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
