# Generated by Django 5.0.3 on 2024-04-24 17:33

import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0089_alter_category_managers_alter_category_site'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sites.site'),
        ),
    ]
