# Generated by Django 5.0.3 on 2024-04-24 17:49

import django.contrib.sites.managers
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0092_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
