# Generated by Django 4.2 on 2024-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0094_alter_blog_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
