# Generated by Django 4.2 on 2024-05-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0095_remove_blog_author_blog_email_alter_comment_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
    ]
