# Generated by Django 4.2 on 2024-05-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0096_alter_blog_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
        migrations.AddField(
            model_name='blog',
            name='footnote',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
