# Generated by Django 4.2 on 2024-05-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0098_alter_blog_category_alter_blog_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
    ]
