# Generated by Django 4.2 on 2024-05-15 21:48

import cms.mixins
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cms', '0099_alter_category_options_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('public', 'Public'), ('unpublish', 'Unpublish'), ('draft', 'Draft')], default='draft', help_text='Default is "draft"', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('main_image', models.ImageField(upload_to=cms.mixins.get_upload_path)),
                ('thumbnail_image', models.ImageField(editable=False, upload_to=cms.mixins.get_upload_path)),
                ('summary', models.TextField(max_length=400)),
                ('footnote', models.TextField(blank=True, max_length=400, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_site', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_access_all', 'Can Access all objects')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
