"""
Django settings for hrdnsh project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
import os

from hrdnsh.conf import LazyCurrentTemplate




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
env = environ.Env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("HRDNSH_SECRET_KEY")

if not SECRET_KEY:
    raise ValueError("No DJANGO_SECRET_KEY set for production!")

# SECURITY WARNING: don't run with debug turned on in production!
ENV_DEBUG = env("HRDNSH_DEBUG")

ALLOWED_HOSTS = ['*']

if ENV_DEBUG.lower() == 'true':
    DEBUG = True
    DYNAMIC_HOST_ALLOW_ALL = True
else:
    DEBUG = False
    DYNAMIC_HOST_ALLOW_ALL = False
    
DYNAMIC_HOSTS_DEFAULT_HOSTS=env("HRDNSH_ALLOWED_HOST").split(',')
DYNAMIC_HOST_ALLOW_SITES=False
DYNAMIC_HOST_RESOLVER_FUNC="common.resolver.check_host"

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'dynamic_host',
    'django_select2',
    'django_summernote',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',    
    
    'account',
    'cms',
    'common',
    'contact',
 
    'django_recaptcha',  
    'project',
    'service'
    
]
TEMPLATE_TAGS = ['django_summernote.templatetags.summernote']
AUTH_USER_MODEL = 'account.User'
AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]

MIDDLEWARE = [
    # 'common.middleware.dynamic_static_middleware',  
    'dynamic_host.middleware.AllowedHostMiddleWare',
    'django.middleware.security.SecurityMiddleware',
        
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sites.middleware.CurrentSiteMiddleware',   
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]


# must be before CURRENT_TEMPLATE
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',        
        'NAME': env("HRDNSH_DB_NAME"),
        'USER': env("HRDNSH_DB_USER"),
        'PASSWORD': env("HRDNSH_DB_PASSWORD"),
        'HOST': env("HRDNSH_DB_HOST"),
        'PORT': env("HRDNSH_DB_PORT"),
        'OPTIONS': {
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

ROOT_URLCONF = 'hrdnsh.urls'

TEMP_DIR = 'temp_dir'

TEMP_UPLOAD_DIR = os.path.join(BASE_DIR, TEMP_DIR) 

CURRENT_TEMPLATE = str(LazyCurrentTemplate())


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, TEMP_DIR, CURRENT_TEMPLATE), os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'common.context_processor.common'
            ]
            
        },
    },
]

WSGI_APPLICATION = 'hrdnsh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30






# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

FILE_UPLOAD_DIRECTORY_PERMISSIONS =0o777
FILE_UPLOAD_PERMISSIONS = 0o644
SESSION_COOKIE_NAME = 'default'

STATIC_URL = f'{TEMP_DIR}/{CURRENT_TEMPLATE}/static/'


if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(TEMP_DIR, CURRENT_TEMPLATE, 'static')
    ]
       
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    
    RECAPTCHA_PUBLIC_KEY = str('6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')
    RECAPTCHA_PRIVATE_KEY = str('6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')
    RECAPTCHA_DOMAIN = 'www.recaptcha.net'
    SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']
else:
    STATIC_ROOT = os.path.join(TEMP_DIR, CURRENT_TEMPLATE, 'static')
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_HOST = True
    SESSION_COOKIE_HTTPONLY = True
    
    RECAPTCHA_PUBLIC_KEY = env("HRDNSH_RECAPTCHA_PUBLIC_KEY")
    RECAPTCHA_PRIVATE_KEY = env("HRDNSH_RECAPTCHA_PRIVATE_KEY")
 
    
    # RECAPTCHA_DOMAIN = 'www.recaptcha.net'
    SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']
    
    

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


DEFAULT_FROM_EMAIL = env("HRDNSH_DEFAULT_FROM_EMAIL")
EMAIL_HOST = env("HRDNSH_EMAIL_HOST")
EMAIL_PORT= env("HRDNSH_EMAIL_PORT")
EMAIL_HOST_USER = env("HRDNSH_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("HRDNSH_EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS=False
EMAIL_USE_SSL=True
ADMIN_EMAIL = env("HRDNSH_ADMIN_EMAIL")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {  
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache'),
        'TIMEOUT': 3600,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

SELECT2_CACHE_BACKEND = 'default'


SUMMERNOTE_THEME = 'bs4'

SUMMERNOTE_CONFIG = {
    'summernote': {    
        # Change editor size
        'width': '100%',
        'height': '480',
        'codemirror': {
            'mode': 'htmlmixed',
            'lineNumbers': 'true',
            'theme': 'monokai'           
        },
    },
    'attachment_require_authentication': True,
    'css': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',
    )
}



FORMATTERS = (
    {
        "verbose": {
            "format": "{levelname} {asctime} {name} {threadName} {thread} {pathname} {lineno} {funcName} {process} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {pathname} {lineno} {message}",
            "style": "{",
        },
    },
)

HANDLERS = {
    "console_handler": {
        "class": "logging.StreamHandler",
        "formatter": "simple",
        "level": "DEBUG"
    },
    "info_handler": {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": os.path.join(BASE_DIR, 'logs/info.log' ),
        "mode": "a",
        "encoding": "utf-8",
        "formatter": "verbose",
        "level": "INFO",
        "backupCount": 5,
        "maxBytes": 1024 * 1024 * 5,  # 5 MB
    },
    "error_handler": {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": os.path.join(BASE_DIR, 'logs/error.log' ),
        "mode": "a",
        "formatter": "verbose",
        "level": "WARNING",
        "backupCount": 5,
        "maxBytes": 1024 * 1024 * 5,  # 5 MB
    },
    'hrdnsh_handler': {
        "filename": os.path.join(BASE_DIR, 'logs/debug.log' ),
        "mode": "a",
        "maxBytes": 1024 * 1024 * 5,  # 5 MB            
        'class': 'logging.handlers.RotatingFileHandler',
        "formatter": "simple",
        "encoding": "utf-8",
        "level": "DEBUG",
        "backupCount": 5,
        
    }
}

LOGGERS = (
    {
        "django": {
            "handlers": ["console_handler", "info_handler"],
            "level": "INFO",
           
        },
        "django.request": {
            "handlers": ["error_handler"],
            'level': 'INFO',             
            "propagate": True,
        },
        "django.template": {
            "handlers": ["error_handler"],
            'level': 'INFO',             
            "propagate": False,
        },
        "django.server": {
            "handlers": ["error_handler"],
            'level': 'INFO',             
            "propagate": True,
        },
        'log': {
            'handlers': ['console_handler', 'hrdnsh_handler'],
            'level': 'INFO', 
            'level': 'DEBUG',   
            "propagate": True,    
            
        },
    },
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": FORMATTERS[0],
    "handlers": HANDLERS,
    "loggers": LOGGERS[0],
}








