# Generated by Django 3.2.8 on 2021-10-17 04:24

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('professional', 'Professional'), ('passionate', 'Passionate')], default='professional', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Write your full name', max_length=100)),
                ('short_title', models.CharField(max_length=150)),
                ('common_slogan', models.CharField(default='The Multitasking Living Machine!', max_length=150)),
                ('picture', models.ImageField(upload_to='card_image')),
                ('card_front', models.ImageField(upload_to='card_image')),
                ('card_back', models.ImageField(upload_to='card_image')),
                ('name_branding', models.ImageField(upload_to='card_image')),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('github_link', models.URLField()),
                ('upwork_link', models.URLField()),
                ('web_address', models.URLField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('current_location', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('aviable_for', taggit.managers.TaggableManager(help_text='Write Comma separated Contract Type eg: remote etc', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Avialable For')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Works title', max_length=200)),
                ('picture', models.ImageField(upload_to='works')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('under_development', 'Under Development')], default='under_development', max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('completed', models.DateField(blank=True, null=True)),
                ('Tag', taggit.managers.TaggableManager(help_text='Write Comma separated work Type eg: eCommerce, Knitwears etc', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tag')),
                ('card', models.ForeignKey(help_text='Select Card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card')),
            ],
            options={
                'ordering': ('-status',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Skills Name', max_length=200)),
                ('proficiency', models.IntegerField(help_text='Enter digit only!')),
                ('practicing_from', models.DateField(blank=True, null=True)),
                ('card', models.ForeignKey(help_text='Select Card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card')),
            ],
            options={
                'ordering': ('-practicing_from',),
            },
        ),
        migrations.CreateModel(
            name='PrCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Profile Category', max_length=200)),
                ('card', models.ForeignKey(help_text='Select Card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card')),
                ('handy_tools', taggit.managers.TaggableManager(help_text='Write Comma separated Contract Type eg: remote etc', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Handy Tools')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Experience title', max_length=200)),
                ('responsibilities', models.TextField()),
                ('start_from', models.DateField(blank=True, null=True)),
                ('card', models.ForeignKey(help_text='Select Card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card')),
            ],
            options={
                'ordering': ('-start_from',),
            },
        ),
    ]
