# Generated by Django 3.2.8 on 2021-10-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_meta', models.CharField(max_length=256)),
                ('site_description', models.TextField(max_length=500)),
                ('site_meta_tag', models.CharField(max_length=256)),
                ('site_favicon', models.ImageField(upload_to='site_image')),
                ('site_logo', models.ImageField(upload_to='site_image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
