# Generated by Django 3.2.8 on 2021-10-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('card', '0003_alter_extendsite_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsite',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extending', to='sites.site'),
        ),
    ]
