# Generated by Django 3.2.8 on 2021-10-17 07:54

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('sites', '0002_alter_domain_unique'),
        ('card', '0005_alter_extendsite_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendsite',
            name='id',
        ),
        migrations.AlterField(
            model_name='extendsite',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profiles', serialize=False, to='sites.site', verbose_name='site'),
        ),
        migrations.RemoveField(
            model_name='extendsite',
            name='site_meta_tag',
        ),
        migrations.AddField(
            model_name='extendsite',
            name='site_meta_tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Meta Tag'),
        ),
    ]
