# Generated by Django 3.2.8 on 2021-10-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20211017_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendsite',
            name='og_image',
            field=models.ImageField(default='', upload_to='site_image'),
            preserve_default=False,
        ),
    ]
