# Generated by Django 3.2.8 on 2021-10-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_extendsite_og_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='common_slogan',
        ),
        migrations.RemoveField(
            model_name='card',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='card',
            name='email',
        ),
        migrations.RemoveField(
            model_name='card',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='card',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='card',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name_branding',
        ),
        migrations.RemoveField(
            model_name='card',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='card',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='card',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='card',
            name='upwork_link',
        ),
        migrations.RemoveField(
            model_name='card',
            name='web_address',
        ),
        migrations.AddField(
            model_name='extendsite',
            name='birth_day',
            field=models.DateField(default='1980-07-11'),
        ),
        migrations.AddField(
            model_name='extendsite',
            name='common_slogan',
            field=models.CharField(default='Multitasking Living Machine', max_length=150),
        ),
        migrations.AddField(
            model_name='extendsite',
            name='current_location',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='facebook_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='github_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='linkedin_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='picture',
            field=models.ImageField(default='', upload_to='card_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='twitter_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='upwork_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='web_address',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
