# Generated by Django 3.2.8 on 2021-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_extendsite_last_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('icon_color', models.CharField(default='#2c2c2c;', max_length=120)),
            ],
        ),
    ]
