# Generated by Django 3.2.8 on 2021-10-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('card', '0011_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='site',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='sites.site', verbose_name='site interest'),
            preserve_default=False,
        ),
    ]
