# Generated by Django 3.2.8 on 2021-10-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('card', '0012_interest_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=500)),
                ('picture', models.ImageField(upload_to='testi_image')),
                ('name', models.CharField(max_length=256)),
                ('job_title', models.CharField(max_length=256)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testi', to='sites.site', verbose_name='site testimonial')),
            ],
        ),
    ]
