# Generated by Django 3.2.8 on 2021-10-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incon_class', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=500)),
                ('card', models.ForeignKey(help_text='Select Card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card')),
            ],
        ),
    ]
