# Generated by Django 3.2.8 on 2021-10-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('card', '0015_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sites.site', verbose_name='ContactsTo'),
        ),
    ]
