# Generated by Django 3.2.8 on 2021-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_alter_contacts_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='subject',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
