# Generated by Django 3.2.8 on 2021-10-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_contacts_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Enter Email'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Messages'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Enter Name'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='subject',
            field=models.CharField(max_length=256, verbose_name='Subject'),
        ),
    ]
