# Generated by Django 3.2.8 on 2021-10-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0018_auto_20211020_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='area',
            field=models.CharField(choices=[('area1', 'Area1'), ('area2', 'Area2')], default='area1', max_length=20, unique=False),
        ),
    ]
