# Generated by Django 3.2.8 on 2021-10-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0021_alter_skills_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=256)),
                ('site_link', models.URLField()),
                ('card', models.ForeignKey(help_text='Select Card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card')),
            ],
        ),
    ]
