# Generated by Django 3.2.8 on 2021-10-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0022_hireme'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='color_code',
            field=models.CharField(default='#2c2c2c', help_text="Write like '#2c2c2c;' with hash and semicolon ", max_length=20),
        ),
    ]
