# Generated by Django 3.2.8 on 2021-10-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0023_experience_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='objective',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
