# Generated by Django 3.2.8 on 2021-10-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0024_card_objective'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ('practicing_from',)},
        ),
        migrations.AddField(
            model_name='experience',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelancing', 'Freelancing'), ('self-business', 'Self Business')], default='full-time', max_length=50),
        ),
    ]
