# Generated by Django 3.2.8 on 2021-10-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0025_auto_20211022_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('start_from',)},
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelancing', 'Freelancing'), ('self_business', 'Self Business')], default='full-time', max_length=50),
        ),
    ]
