# Generated by Django 3.2.8 on 2021-10-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0026_auto_20211022_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cv_image',
            field=models.ImageField(default='', upload_to='cv_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='cv_logo',
            field=models.ImageField(default='', upload_to='cv_image'),
            preserve_default=False,
        ),
    ]
