# Generated by Django 3.2.8 on 2021-10-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0027_auto_20211023_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('contact', 'Contact'), ('signup', 'Signup'), ('service_inquery', 'service_inquery')], default='contact', max_length=50, unique=True)),
                ('to_subject', models.CharField(max_length=256)),
                ('to_message', models.TextField(max_length=1000)),
                ('admin_subject', models.CharField(max_length=256)),
                ('admin_message', models.TextField(max_length=1000)),
            ],
        ),
    ]
