# Generated by Django 3.2.8 on 2021-10-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0028_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendsite',
            name='email_host',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='email_host_pass',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='email_host_user',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendsite',
            name='email_port',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
