# Generated by Django 3.2.8 on 2021-10-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0031_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='s1', unique=True),
        ),
    ]
