# Generated by Django 3.2.8 on 2021-10-24 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0032_alter_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('service', models.ForeignKey(help_text='Select Service name', on_delete=django.db.models.deletion.CASCADE, to='card.service')),
            ],
        ),
    ]
