# Generated by Django 3.2.8 on 2021-10-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0035_works_work_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='admin_message',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='admin_subject',
        ),
    ]
