# Generated by Django 3.2.8 on 2021-10-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0036_auto_20211025_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='signature',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
