# Generated by Django 3.2.8 on 2021-11-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0039_auto_20211109_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
