# Generated by Django 5.0.3 on 2024-04-21 05:05

import django.contrib.sites.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_remove_siteprofile_name_logo_svg_and_more'),
        ('service', '0008_alter_service_site'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='skills',
            field=models.ManyToManyField(related_name='service_skills', to='common.skillsandtools'),
        ),
        migrations.AlterField(
            model_name='service',
            name='site',
            field=models.ForeignKey(default=django.contrib.sites.models.SiteManager.get_current, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_site', to='sites.site'),
        ),
    ]
