# Generated by Django 5.0.3 on 2024-04-21 10:28

import django.contrib.sites.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_service_svg_icon_alter_service_site'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='site',
            field=models.ForeignKey(default=django.contrib.sites.models.SiteManager.get_current, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_site', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='service',
            name='svg_icon',
            field=models.FileField(upload_to='service_icon_svg/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
