# Generated by Django 4.2 on 2024-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_alter_service_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='author',
        ),
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
