# Generated by Django 4.2 on 2024-05-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_remove_service_author_service_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
    ]
