# Generated by Django 4.2 on 2024-05-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0098_alter_blog_category_alter_blog_status_and_more'),
        ('service', '0032_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Must be picked from Category of the site (cms_site_category_list)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_category', to='cms.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('unpublish', 'Unpublish'), ('draft', 'Draft')], default='draft', help_text='Default is "draft"', max_length=10),
        ),
    ]
