# Generated by Django 4.2 on 2024-05-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_alter_service_category_alter_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='email',
        ),
    ]
