# Generated by Django 4.2 on 2024-11-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_remove_service_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='buy_link',
            field=models.URLField(blank=True, help_text='buy link from any payment gateway', null=True),
        ),
    ]
