# Generated by Django 4.2 on 2024-11-25 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_service_buy_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=20)),
                ('buy_link', models.URLField(help_text='Direct Payment URL from Strip')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_options', to='service.service')),
            ],
        ),
    ]
