# Generated by Django 4.2 on 2024-11-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0036_priceoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='buy_link',
        ),
    ]
