# Generated by Django 5.0.3 on 2024-04-25 09:46

import cms.mixins
import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('public', 'Public'), ('unpublish', 'Unpublish'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('main_image', models.ImageField(upload_to=cms.mixins.get_upload_path)),
                ('thumbnail_image', models.ImageField(editable=False, upload_to=cms.mixins.get_upload_path)),
                ('summary', models.TextField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_site', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            bases=(cms.mixins.SaveAndImageOptimizationMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('project', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.project')),
                ('item', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectScoope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.PositiveIntegerField(help_text='Integer accepted')),
                ('scoope', models.TextField(max_length=1000)),
                ('outcome', models.TextField(blank=True, max_length=1000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scoopes', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
