# Generated by Django 5.0.3 on 2024-04-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='body',
        ),
    ]
