# Generated by Django 5.0.3 on 2024-04-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRequirement',
        ),
    ]
