# Generated by Django 5.0.3 on 2024-04-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequirement',
            name='item',
            field=models.CharField(max_length=250),
        ),
    ]
