# Generated by Django 5.0.3 on 2024-04-25 11:01

import cms.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectrequirement_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoopVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to=cms.mixins.get_upload_path)),
                ('thumbnail_image', models.ImageField(editable=False, upload_to=cms.mixins.get_upload_path)),
                ('project_scoope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoope_visualization', to='project.projectscoope')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
