# Generated by Django 5.0.3 on 2024-04-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0094_alter_blog_site'),
        ('project', '0006_scoopvisualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_category', to='cms.category'),
        ),
    ]
