# Generated by Django 5.0.3 on 2024-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0094_alter_blog_site'),
        ('project', '0007_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_categories', to='cms.category'),
        ),
    ]
