# Generated by Django 5.0.3 on 2024-04-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_project_category_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categories',
        ),
    ]
