# Generated by Django 4.2 on 2024-05-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_project_author_project_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
    ]
