# Generated by Django 4.2 on 2024-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoopvisualization',
            name='site',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('unpublish', 'Unpublish'), ('draft', 'Draft')], default='draft', help_text='Default is "draft"', max_length=10),
        ),
    ]
