# Generated by Django 4.2 on 2024-05-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_scoopvisualization_site_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
    ]
