# Generated by Django 4.2 on 2024-05-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_project_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at', 'title'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={'ordering': ['item'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='projectscoope',
            options={'ordering': ['step'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
        migrations.AlterModelOptions(
            name='scoopvisualization',
            options={'ordering': ['pk'], 'permissions': [('can_access_all', 'Can Access all objects')]},
        ),
    ]
